"""Small, deterministic output writers for reconstruction diagnostics."""

from __future__ import annotations

from pathlib import Path

import numpy as np
from numpy.typing import NDArray
from PIL import Image, ImageDraw

from cozmo_scan.models import ReconstructionSummary
from cozmo_scan.reconstruction import ReconstructionResult

POINT_CLOUD_FILENAME = "reconstruction.ply"
TOPDOWN_FILENAME = "topdown.png"
SUMMARY_FILENAME = "reconstruction.json"
RECONSTRUCTION_FILENAMES = (
    POINT_CLOUD_FILENAME,
    TOPDOWN_FILENAME,
    SUMMARY_FILENAME,
)


class OutputError(ValueError):
    """Raised when reconstruction artifacts cannot be written safely."""


def write_reconstruction_outputs(
    result: ReconstructionResult,
    output_directory: str | Path,
    *,
    overwrite: bool = False,
) -> dict[str, Path]:
    """Write the complete CP03 diagnostic artifact set."""
    directory = Path(output_directory)
    if directory.exists() and not directory.is_dir():
        raise OutputError(f"Output path is not a directory: {directory}")

    existing = [directory / name for name in RECONSTRUCTION_FILENAMES]
    conflicts = [path for path in existing if path.exists()]
    if conflicts and not overwrite:
        names = ", ".join(path.name for path in conflicts)
        raise OutputError(
            f"Output artifacts already exist ({names}); pass --overwrite to replace them"
        )

    directory.mkdir(parents=True, exist_ok=True)
    paths = {
        "point_cloud": directory / POINT_CLOUD_FILENAME,
        "topdown_preview": directory / TOPDOWN_FILENAME,
        "summary": directory / SUMMARY_FILENAME,
    }
    write_ply(paths["point_cloud"], result.points_xyz_m)
    render_topdown(
        paths["topdown_preview"],
        result.points_xyz_m,
        result.trajectory_xyz_m,
    )
    write_reconstruction_summary(paths["summary"], result.summary)
    return paths


def write_ply(path: str | Path, points_xyz_m: NDArray[np.floating]) -> None:
    """Write XYZ points as a compact binary little-endian PLY file."""
    points = np.asarray(points_xyz_m)
    if points.ndim != 2 or points.shape[1] != 3:
        raise OutputError("PLY points must have shape (N, 3)")
    if not np.isfinite(points).all():
        raise OutputError("PLY points contain non-finite values")

    destination = Path(path)
    temporary = destination.with_name(f"{destination.name}.tmp")
    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        "comment generated by cozmo-scan\n"
        f"element vertex {len(points)}\n"
        "property float x\n"
        "property float y\n"
        "property float z\n"
        "end_header\n"
    ).encode("ascii")
    try:
        with temporary.open("wb") as stream:
            stream.write(header)
            np.asarray(points, dtype="<f4").tofile(stream)
        temporary.replace(destination)
    except OSError as exc:
        temporary.unlink(missing_ok=True)
        raise OutputError(f"Cannot write PLY output: {destination}") from exc


def render_topdown(
    path: str | Path,
    points_xyz_m: NDArray[np.floating],
    trajectory_xyz_m: NDArray[np.floating] | None = None,
    *,
    image_size: int = 1000,
) -> None:
    """Render a robust X-Z density view with an optional camera trajectory."""
    points = np.asarray(points_xyz_m)
    if points.ndim != 2 or points.shape[1] != 3 or len(points) == 0:
        raise OutputError("Top-down points must be a non-empty array with shape (N, 3)")
    if image_size < 64:
        raise OutputError("Top-down image_size must be at least 64 pixels")

    finite = points[np.isfinite(points).all(axis=1)]
    if len(finite) == 0:
        raise OutputError("Top-down points contain no finite values")
    x = finite[:, 0]
    z = finite[:, 2]
    x_min, x_max = _robust_axis_range(x)
    z_min, z_max = _robust_axis_range(z)

    trajectory = None
    if trajectory_xyz_m is not None:
        candidate = np.asarray(trajectory_xyz_m)
        if candidate.ndim == 2 and candidate.shape[1] == 3:
            trajectory = candidate[np.isfinite(candidate).all(axis=1)]
            if len(trajectory):
                x_min = min(x_min, float(trajectory[:, 0].min()))
                x_max = max(x_max, float(trajectory[:, 0].max()))
                z_min = min(z_min, float(trajectory[:, 2].min()))
                z_max = max(z_max, float(trajectory[:, 2].max()))
                x_min, x_max = _pad_axis_range(x_min, x_max)
                z_min, z_max = _pad_axis_range(z_min, z_max)

    histogram, _, _ = np.histogram2d(
        z,
        x,
        bins=(image_size, image_size),
        range=((z_min, z_max), (x_min, x_max)),
    )
    density = np.log1p(histogram)
    if density.max() > 0:
        density /= density.max()
    grayscale = 255 - np.asarray(density * 235, dtype=np.uint8)
    image = Image.fromarray(np.flipud(grayscale), mode="L").convert("RGB")

    if trajectory is not None and len(trajectory):
        _draw_trajectory(
            image,
            trajectory,
            x_range=(x_min, x_max),
            z_range=(z_min, z_max),
        )

    destination = Path(path)
    temporary = destination.with_name(f"{destination.name}.tmp")
    try:
        image.save(temporary, format="PNG")
        temporary.replace(destination)
    except OSError as exc:
        temporary.unlink(missing_ok=True)
        raise OutputError(f"Cannot write top-down output: {destination}") from exc


def write_reconstruction_summary(
    path: str | Path, summary: ReconstructionSummary
) -> None:
    """Write the diagnostic summary as formatted UTF-8 JSON."""
    destination = Path(path)
    temporary = destination.with_name(f"{destination.name}.tmp")
    try:
        temporary.write_text(summary.model_dump_json(indent=2) + "\n", encoding="utf-8")
        temporary.replace(destination)
    except OSError as exc:
        temporary.unlink(missing_ok=True)
        raise OutputError(f"Cannot write reconstruction summary: {destination}") from exc


def _robust_axis_range(values: NDArray[np.floating]) -> tuple[float, float]:
    lower, upper = np.percentile(values, (0.5, 99.5))
    if not np.isfinite([lower, upper]).all():
        raise OutputError("Cannot determine a finite top-down range")
    if upper - lower < 1e-6:
        centre = float((upper + lower) / 2)
        return centre - 0.5, centre + 0.5
    padding = float(upper - lower) * 0.05
    return float(lower - padding), float(upper + padding)


def _pad_axis_range(lower: float, upper: float) -> tuple[float, float]:
    if upper - lower < 1e-6:
        centre = (upper + lower) / 2
        return centre - 0.5, centre + 0.5
    padding = (upper - lower) * 0.05
    return lower - padding, upper + padding


def _draw_trajectory(
    image: Image.Image,
    trajectory: NDArray[np.floating],
    *,
    x_range: tuple[float, float],
    z_range: tuple[float, float],
) -> None:
    width, height = image.size
    x_min, x_max = x_range
    z_min, z_max = z_range
    finite = trajectory[np.isfinite(trajectory).all(axis=1)]
    if len(finite) == 0:
        return

    pixels: list[tuple[int, int]] = []
    for point in finite:
        x_fraction = (float(point[0]) - x_min) / (x_max - x_min)
        z_fraction = (float(point[2]) - z_min) / (z_max - z_min)
        pixel_x = round(np.clip(x_fraction, 0.0, 1.0) * (width - 1))
        pixel_y = round((1.0 - np.clip(z_fraction, 0.0, 1.0)) * (height - 1))
        pixels.append((pixel_x, pixel_y))

    drawing = ImageDraw.Draw(image)
    if len(pixels) > 1:
        drawing.line(pixels, fill=(220, 30, 30), width=3)
    radius = 6
    _draw_marker(drawing, pixels[0], radius, (20, 170, 20))
    _draw_marker(drawing, pixels[-1], radius, (30, 90, 220))


def _draw_marker(
    drawing: ImageDraw.ImageDraw,
    position: tuple[int, int],
    radius: int,
    color: tuple[int, int, int],
) -> None:
    x, y = position
    drawing.ellipse((x - radius, y - radius, x + radius, y + radius), fill=color)
